// This file is auto-generated by @hey-api/openapi-ts

/**
 * An enumeration.
 */
export type AvailableModels = "gpt-3.5-turbo";

export type ChatStreamRequest = {
  messages: Array<Message>;
  model: AvailableModels;
};

export type EmbeddingResponse = {
  data: Array<number>;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type Message = {
  role: Role;
  content: string;
};

/**
 * An enumeration.
 */
export type Role = "system" | "user" | "assistant";

export type SpacyProcessResponse = {
  data: Array<SpacyToken>;
};

export type SpacyToken = {
  text: string;
  pos: string;
  dep: string;
  lemma: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type $OpenApiTs = {
  // "/": {
  //   get: {
  //     res: {
  //       /**
  //        * Successful Response
  //        */
  //       200: unknown;
  //     };
  //   };
  // };
  "/embed": {
    get: {
      req: {
        text: string;
      };
      res: {
        /**
         * Successful Response
         */
        200: EmbeddingResponse;
      };
    };
  };
  "/process": {
    get: {
      req: {
        text: string;
      };
      res: {
        /**
         * Successful Response
         */
        200: SpacyProcessResponse;
      };
    };
  };
  "/chat/stream": {
    post: {
      req: {
        requestBody: ChatStreamRequest;
      };
      res: {
        /**
         * Successful Response
         */
        200: any;
      };
    };
  };
};
