import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import { cn } from "~/lib/utils";
import { ThemeProvider } from "~/components/theme/provider";
import { Toaster } from "~/components/ui/sonner";
import { OpenAIKeyProvider } from "~/components/openai/key-provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Jotta Spanish",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const openAIKey = process.env.OPENAI_API_KEY;
  return (
    <html lang="en">
      <body className={cn(inter.className, "antialiased")}>
        <TRPCReactProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <OpenAIKeyProvider initialKey={openAIKey}>
              {children}
              <Toaster />
            </OpenAIKeyProvider>
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
