import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import { cn } from "~/lib/utils";
import { ThemeProvider } from "~/components/theme/provider";
import { Toaster } from "~/components/ui/sonner";
import { OpenAIKeyProvider } from "~/components/openai/key-provider";
import { OpenAPI } from "~/lib/python_client";
import { env } from "~/env";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Jotta Spanish",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const openAIKey = env.OPENAI_API_KEY;

  OpenAPI.BASE = `https://${env.MODAL_USER}-${env.MODAL_ENV}--${env.MODAL_ROUTER_APP}.modal.run`;
  OpenAPI.interceptors.request.use((request) => {
    request.headers = {
      ...request.headers,
      Authorization: `Bearer ${env.MODAL_ROUTER_AUTH_TOKEN}`,
    };
    return request;
  });

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, "antialiased")}>
        <div>
          <TRPCReactProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <OpenAIKeyProvider initialKey={openAIKey}>
                {children}
                <Toaster />
              </OpenAIKeyProvider>
            </ThemeProvider>
          </TRPCReactProvider>
        </div>
      </body>
    </html>
  );
}
