name: modal-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Modal
        run: |
          python -m pip install --upgrade pip
          pip install modal

      - name: Deploy Models
        run: |
          find python/deployments -maxdepth 2 -type f -path '*/stub.py' -exec sh -c 'modal deploy --env ${MODAL_ENV} python.deployments.$(basename $(dirname {})).stub' \;

      - name: Deploy Router
        run: |
          modal deploy --env ${MODAL_ENV} python.router
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      MODAL_ENV: ${{ vars.MODAL_ENV }}
